### ISSUE TITLE
Expose colors as options

### ISSUE THREAD

**Issue by jednano** [sindresorhus/jshint-stylish#10]
On Windows, I'm getting unsightly blue-on-black text, which is really hard to read. If the colors were exposed as options, however, I could fix this quite easily!

**Comment by d-oliveros** [comment]
I'm also breaking my head trying to change `jshint-stylish` colors. Using a dark background with a little bit of opacity, the text is unreadable.

**Comment by d-oliveros** [comment]
By the way, I actually changed my bash colors, it doesn't really change the color `jshint-stylish`.
