### ISSUE TITLE
V2: Grunt Reporter toString

### ISSUE THREAD

**Issue by ianma** [sindresorhus/jshint-stylish#22]
When upgrading from v1 to v2, I had to update my grunt task from `reporter: require('jshint-stylish')` to `reporter: require('jshint-stylish').toString()`. Can you confirm that is what's expected? If so, perhaps the [documentation for grunt-contrib-jshint](https://github.com/sindresorhus/jshint-stylish/tree/1e20faca42a1aebddc2780b72f853e2dafedfb3e#grunt-contrib-jshint) should be updated.

**Comment by sindresorhus** [comment]
Upgrade grunt-contrib-jshint https://github.com/sindresorhus/jshint-stylish/pull/20

**Comment by ianma** [comment]
Thanks, upgrading to `"grunt-contrib-jshint": "^0.11"` fixed it. Is this a case where specifying a peerDependency would help?

**Comment by sindresorhus** [comment]
Not really, as this reporter works with a lot of other JSHint tools other than grunt-contrib-jshint. Just make sure to always be on latest of everything as the first resort of trying to resolve an issue.
