### ISSUE TITLE
Error on generator function in a class

### ISSUE THREAD

**Issue by kristianmandrup** [sindresorhus/jshint-stylish#23]
I'm getting this error:

https://github.com/jshint/jshint/issues/1978

```js
export default class RouteBuilder {
  ...
  renderPage*() {
    this.render(this, this.name, this.appData(this.name));
  }
```

Running with jshint-stylish

```sh
    Unexpected token * at server/routes/route-builder.js :
    25 |  }
    26 |
    27 |  renderPage*() {
```

Actually I really just want to get the function reference, so I guess I should turn it into a getter and return the generator function from there, thus achieving what I want without error ;) 

But still, should this case should not cause a jshint error IMO.
Thanks ;)

**Comment by sindresorhus** [comment]
No idea why you're posting this here, but should be posted on the JSHint issue tracker.
