### ISSUE TITLE
Documentation needs to be updated on how to use version 2 with `grunt-contrib-jshint`

### ISSUE THREAD

**Issue by yorch** [sindresorhus/jshint-stylish#24]
From version 2, when using with `grunt-contrib-jshint` a usage change needs to happen:

```
grunt.initConfig({
    jshint: {
        options: {
            reporter: require('jshint-stylish').toString()
        },
        target: ['file.js']
    }
});
```

Unless I'm missing something.

Thanks

**Comment by sindresorhus** [comment]
> a usage change needs to happen:

No.

> Unless I'm missing something.

Yes → https://github.com/sindresorhus/jshint-stylish/pull/20
