### ISSUE TITLE
Warning icon

### ISSUE THREAD

**Issue by linlinlinlin** [sindresorhus/jshint-stylish#25]
The icon of the warning result I cannot display correctly. Does it have to install other plug-in first?

**Comment by sindresorhus** [comment]
Can you include a screenshot? If you mean you get `‼` instead, it's because your on Windows and it doesn't support Unicode on the command-line, so we're using a fallback symbol.

**Comment by linlinlinlin** [comment]
Like this:

![warning](https://cloud.githubusercontent.com/assets/8558312/9459956/c952fcea-4b33-11e5-95e2-d39560198482.PNG)

My environment on Ubuntu.

**Comment by sindresorhus** [comment]
I don't think there's anything I can do about that. Ubuntu supports that font, but Windows doesn't. I have no way to check that your using Ubuntu from Windows. PR welcome if anyone knows a fix, but I highly doubt it.
