### ISSUE TITLE
Show failing line

### ISSUE THREAD

**Issue by techtonik** [sindresorhus/jshint-stylish#27]
Grunt reporter shows line when jshint check fails. It would be nice if `jshint-stylish` could support this too.

Here is the comparisons. `jshint-stylish` is run by Gulp.
https://travis-ci.org/gratipay/grtp.co/builds/89160580

**Comment by sindresorhus** [comment]
Yeah, that can be useful, but it would make `jshint-stylish` something completely different from what it currently is. Make a new reporter ;)

**Comment by techtonik** [comment]
@sindresorhus can you expand why adding line reporting will make it something completely different from `jshint-stylish`?

Is it possible to provide line reporting as an option?

Do you know other reporters that can provide such info?

**Comment by sindresorhus** [comment]
Because the output will be completely different. Not interested in an option. Just make or use another reporter if you need this. No idea which though. I don't use JSHint anymore.

**Comment by techtonik** [comment]
What do you use instead of JSHint?

**Comment by techtonik** [comment]
If somebody decides to hack on that - the code needs to print `evidence`. The particular output in Travis was generated by this code https://github.com/gruntjs/grunt-contrib-jshint/blob/master/tasks/lib/jshint.js#L106

**Comment by sindresorhus** [comment]
ESlint. It's much better.

**Comment by techtonik** [comment]
Thanks.

https://www.npmjs.com/package/gulp-eslint
