### ISSUE TITLE
show jshint rule related to the error in stylish output

### ISSUE THREAD

**Issue by obuckley-kenzan** [sindresorhus/jshint-stylish#28]
Not sure if this would be for here, the jshint team, or the gulp-jshint team, but would it be possible to see the jshint rule related to the thrown error, either by default or as config option?

for example, if the error is 
`line 16  col 14  'cardPayment' is not defined.`

we would also see this as part of the output
`/* jshint -W117 */`

Thanks and keep up the great work!

**Comment by sindresorhus** [comment]
Duplicate of #14.

**Comment by obuckley-kenzan** [comment]
Thanks, will follow up with the gulp-jshint team
