### ISSUE TITLE
How do I found total number of error among all files ?

### ISSUE THREAD

**Issue by osi-bhushankumar** [sindresorhus/jshint-stylish#32]
How can we obtain number of total error ('10 error') among all scanned file or something which shows total number of error/warning scanned after jshint.

**Comment by sindresorhus** [comment]
It's displayed at the bottom of the output.

**Comment by osi-bhushankumar** [comment]
@sindresorhus , Currently it's showing file wise output File1.js (5 errors), File2.js (3 errors).

At the end of 'Total Number of Errors/Warning among all file are 8'.

**Comment by sindresorhus** [comment]
No, it shows at the end of the result. It's probably your JSHint runner doing something wrong, like running reporters one per file or something.

**Comment by osi-bhushankumar** [comment]
oh!. Can you help me to resolve this on configure my jshint properly, this is my configure for jshint ?

    gulp.task('jshint', function () {
      return gulp.src(['*.js', 'www/js/app.js', 'www/js/app.routes.js', 'www/js/app.configs.js',
        'www/app/**/*.js', 'www/services/*.js', 'www/services/**/*.js', 'www/models/*.js'])
        .pipe(jshint())
        .pipe(jshint.reporter('jshint-stylish', {verbose: true})).on('error', function (error) {
        });
    });
