### ISSUE TITLE
Add fullPath option

### ISSUE THREAD

**Issue by asanin-2sol** [sindresorhus/jshint-stylish#34]
Hi,

The reporter currently prints relative paths to the console.
In some IDEs, the terminal only converts absolute paths into clickable links, which is really
useful for quickly navigating to the errors.

Could you add a 'fullPath' option to the reporter?

I guess all you would have to do is adding:

```
var path = require("path");
```

and replacing line 35 with:

```
headers[i] = (options.fullPath ? path.resolve(process.cwd(), el.file) : el.file);
```

Thanks :)

**Comment by sindresorhus** [comment]
This reporter just prints whatever it get's from JSHint. I think it would be better implemented there. https://github.com/sindresorhus/jshint-stylish/blob/ef2196704fdc9c034549ff82048989d5fb8cf2a8/index.js#L35

**Comment by asanin-2sol** [comment]
Thanks.

For anyone interested, it seems they are already discussing the possibility of a ```--reporter:fullpath``` flag on jshint:
https://github.com/jshint/jshint/issues/2752

**Comment by roscorcoran** [comment]
I found a quick fix solution for those using Gulp, you can pipe to your own reporter inline in your gulpfile and modify the file string:

```
    .pipe(jshint.reporter(
      module.exports = {
      reporter: function (results) {
        results.forEach(function (result) {
          result.file = process.cwd() + '/' + result.file  + ':' + result.error.line + ':' + result.error.character;
        });
      }
    }))
```

So you would place this between the jshint output and the jshint-stylish reporter. like this:

```
    .pipe(jshint())
    .pipe(jshint.reporter(
      module.exports = {
      reporter: function (results) {
        results.forEach(function (result) {
          result.file = process.cwd() + '/' + result.file  + ':' + result.error.line + ':' + result.error.character;
        });
      }
    }))
    .pipe(jshint.reporter('jshint-stylish', {verbose: true}));
```

Let me know if this works for anyone.

**Comment by asanin-2sol** [comment]
@roscorcoran nice approach, works for me :)
