### ISSUE TITLE
gray line number not visible

### ISSUE THREAD

**Issue by Neats29** [sindresorhus/jshint-stylish#37]
Hi, thanks for creating this module.

Is there any way we could control the colours of the outputs passed as options?
This is what I want to change in particular: https://github.com/sindresorhus/jshint-stylish/blob/master/index.js#L30

Because the grey clashes with mine and my colleagues' terminal background colour, so we can't actually see the line numbers.

Thanks.

**Comment by sindresorhus** [comment]
No, and not interested in an option for that. Are you gonna open an issue on every single module that uses gray or just fix the gray in your terminal theme?
