### ISSUE TITLE
Colors on windows are hard to read

### ISSUE THREAD

**Issue by ScottWeinstein** [sindresorhus/jshint-stylish#7]
Perhaps not the most important thing, but the colors on a default windows console are pretty hard to read

![image](https://f.cloud.github.com/assets/263024/2144232/42a7f8b8-9382-11e3-8ae6-43fa65e60351.png)

**Comment by pavelhoral** [comment]
FYI this is problem in KDE's Konsole as well with almost any color preset. And BTW the response "fix your console" is kind of strange.
